# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['lang'], name='news_articl_lang_87047b_idx'),
        ),
    ]
